# Generated by Django 4.1.7 on 2023-03-11 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_static', models.BooleanField(default=False)),
                ('cart_limit', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('amount_limit', models.TextField(blank=True, null=True)),
                ('percent_limit', models.TextField(blank=True, null=True)),
                ('valid_date', models.DateField(blank=True, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Static_coupens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_coupens', models.IntegerField(blank=True, null=True)),
                ('coupens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupens_static', to='coupons.coupens')),
            ],
        ),
        migrations.CreateModel(
            name='Dynamic_coupens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_date', models.DateField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('coupens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupens_dynamic', to='coupons.coupens')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupen_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
