# Generated by Django 4.1.7 on 2023-03-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_coupens_is_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic_coupens',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
