# Generated by Django 4.1.7 on 2023-03-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_alter_dynamic_coupens_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupens',
            name='code',
        ),
        migrations.AddField(
            model_name='static_coupens',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
