# Generated by Django 3.1 on 2023-03-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_remove_coupens_code_static_coupens_code'),
        ('coupons', '0005_auto_20230311_1849'),
    ]

    operations = [
    ]
