# Generated by Django 4.1.7 on 2023-03-11 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userdata_referrals_left_userdata_user'),
        ('coupons', '0008_alter_coupens_id_alter_dynamic_coupens_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupens',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.adminprofile'),
        ),
    ]
