# Generated by Django 4.1.7 on 2023-03-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_adminprofile_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='gst',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='pan',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
