# Generated by Django 4.1.7 on 2023-03-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userdata_referrals_left_userdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_of_referrals',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
